default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
test:
  primary:
    <<: *default
    database: storage/test<%= ENV['TEST_ENV_NUMBER'] %>.sqlite3
  queue:
    <<: *default
    database: storage/test_queue<%= ENV['TEST_ENV_NUMBER'] %>.sqlite3
  railwatch:
    <<: *default
    database: storage/test_railwatch<%= ENV['TEST_ENV_NUMBER'] %>.sqlite3
  railwatch_telemetry:
    <<: *default
    database: storage/test_railwatch_telemetry<%= ENV['TEST_ENV_NUMBER'] %>.sqlite3
development:
  <<: *default
  database: storage/development.sqlite3
