default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
test:
  primary:
    <<: *default
    database: storage/test.sqlite3
  queue:
    <<: *default
    database: storage/test_queue.sqlite3
development:
  <<: *default
  database: storage/development.sqlite3
