/**
 * @file Generated by js-routes 2.4.1. Based on Rails 8.1.3.1 routes of RailwatchCloud::Application.
 * @version 0cf9935e83800f447807f71c7bc3141106e939ff751799ef61b3dc635feaeb83
 * @see https://github.com/railsware/js-routes
 */
type Optional<T> = {
    [P in keyof T]?: T[P] | null;
};
export type Collection<T> = Record<string, T>;
type BaseRouteParameter = string | boolean | Date | number | bigint;
type MethodRouteParameter = BaseRouteParameter | (() => BaseRouteParameter);
type ModelRouteParameter = {
    id: MethodRouteParameter;
} | {
    to_param: MethodRouteParameter;
} | {
    toParam: MethodRouteParameter;
};
type RequiredRouteParameter = BaseRouteParameter | ModelRouteParameter;
type OptionalRouteParameter = undefined | null | RequiredRouteParameter;
type QueryRouteParameter = OptionalRouteParameter | QueryRouteParameter[] | {
    [k: string]: QueryRouteParameter;
};
export type RouteParameters = Collection<QueryRouteParameter>;
type Serializable = Collection<unknown>;
export type Serializer = (value: Serializable) => string;
type RouteHelperExtras = {
    requiredParams(): string[];
    toString(): string;
};
type RequiredParameters<T extends number> = T extends 1 ? [RequiredRouteParameter] : T extends 2 ? [RequiredRouteParameter, RequiredRouteParameter] : T extends 3 ? [RequiredRouteParameter, RequiredRouteParameter, RequiredRouteParameter] : T extends 4 ? [
    RequiredRouteParameter,
    RequiredRouteParameter,
    RequiredRouteParameter,
    RequiredRouteParameter
] : RequiredRouteParameter[];
type RouteHelperOptions = RouteOptions & Collection<OptionalRouteParameter>;
export type RouteHelper<T extends number = number> = ((...args: [...RequiredParameters<T>, RouteHelperOptions]) => string) & RouteHelperExtras;
type Configuration = {
    prefix: string;
    default_url_options: RouteParameters;
    special_options_key: string;
    serializer: Serializer;
    deprecated_false_parameter_behavior: boolean;
    deprecated_nil_query_parameter_behavior: boolean;
    include_undefined_query_parameters: boolean;
};
export interface RouterExposedMethods {
    config(): Configuration;
    configure(arg: Partial<Configuration>): Configuration;
    serialize: Serializer;
    __route(...args: unknown[]): RouteHelper;
}
export interface RouterConstructor {
    new (config?: Partial<Configuration>): RouterExposedMethods;
}
type KeywordUrlOptions = Optional<{
    host: string;
    protocol: string;
    subdomain: string;
    port: string | number;
    anchor: string;
    trailing_slash: boolean;
    script_name: string;
    params: RouteParameters;
}>;
type RouteOptions = KeywordUrlOptions & RouteParameters;
export {};
export const configure: RouterExposedMethods['configure'];

export const config: RouterExposedMethods['config'];

export const serialize: RouterExposedMethods['serialize'];

export const __route: RouterExposedMethods['__route'];

/**
 * Generates rails route to
 * /invitations/:token(.:format)
 * @param {any} token
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const acceptInvitationPath: ((
  token: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /accounts/:id(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const accountPath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /accounts(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const accountsPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /alerts(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const alertsPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/accounts(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1AccountsPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/applications/:id(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1ApplicationPath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/applications/:application_id/environments/:id(.:format)
 * @param {any} applicationId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1ApplicationEnvironmentPath: ((
  applicationId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/applications(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1ApplicationsPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/applications/:application_id/environments/:environment_id/deploys(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1EnvironmentDeploysPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/applications/:application_id/environments/:environment_id/exceptions(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1EnvironmentExceptionsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/applications/:application_id/environments/:environment_id/executions/:execution_id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} executionId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1EnvironmentExecutionPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  executionId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/applications/:application_id/environments/:environment_id/jobs(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1EnvironmentJobsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/applications/:application_id/environments/:environment_id/logs(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1EnvironmentLogsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/applications/:application_id/environments/:environment_id/queries(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1EnvironmentQueriesPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/applications/:application_id/environments/:environment_id/releases(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1EnvironmentReleasesPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/applications/:application_id/environments/:environment_id/requests/:group_hash(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} groupHash
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1EnvironmentRequestGroupPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  groupHash: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/applications/:application_id/environments/:environment_id/requests(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1EnvironmentRequestsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/applications/:application_id/environments/:environment_id/series(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1EnvironmentSeriesPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/applications/:application_id/environments/:environment_id/spans(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1EnvironmentSpansPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/applications/:application_id/environments/:environment_id/summary(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1EnvironmentSummaryPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/applications/:application_id/environments/:environment_id/tenants(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1EnvironmentTenantsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/applications/:application_id/environments/:environment_id/users(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1EnvironmentUsersPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/issues/:id(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1IssuePath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/issues/:issue_id/comments(.:format)
 * @param {any} issueId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1IssueCommentsPath: ((
  issueId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/issues(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1IssuesPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /api/v1/me(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const apiV1MePath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:id(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationPath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:id(.:format)
 * @param {any} applicationId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentPath: ((
  applicationId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/alerts(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentAlertsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/anomaly_rules/:id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentAnomalyRulePath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/anomaly_rules(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentAnomalyRulesPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/attachments/:id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentAttachmentPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/broadcasts(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentBroadcastsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/cache(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentCacheEventsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/commands/:id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentCommandPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/commands(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentCommandsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/deploys/:id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentDeployPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/deploys(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentDeploysPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/deprecations(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentDeprecationsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/exceptions(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentExceptionsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/executions/:id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentExecutionPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/jobs/:id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentJobPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/jobs(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentJobsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/llm(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentLlmCallsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/logs(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentLogsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/mail(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentMailsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/monitoring_health(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentMonitoringHealthPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/notifications(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentNotificationsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/outgoing_requests(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentOutgoingRequestsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentOverviewPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/users(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentPeoplePath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/users/:id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentPersonPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/processes(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentProcessesPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/profiles/:id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentProfilePath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/profiles(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentProfilesPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/queries(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentQueriesPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/queries/:id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentQueryPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/releases/:id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentReleasePath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/releases(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentReleasesPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/requests/:id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentRequestPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/requests(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentRequestsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/saved_views/:id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentSavedViewPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/saved_views(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentSavedViewsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/scheduled_tasks/:id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentScheduledTaskPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/scheduled_tasks(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentScheduledTasksPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/spans/:id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentSpanPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/spans(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentSpansPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/storage(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentStorageOpsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/tenants/:id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentTenantPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/tenants(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentTenantsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/thresholds/:id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentThresholdPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/thresholds(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentThresholdsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/traces/:trace_id(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} traceId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentTracePath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  traceId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/transactions(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentTransactionsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/usage(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentUsagePath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/views(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentViewRendersPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/visits(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentVisitsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs(.:format)
 * @param {any} applicationId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationEnvironmentsPath: ((
  applicationId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const applicationsPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /auth/failure(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const authFailurePath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /issues/bulk(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const bulkIssuesPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/linear_oauth/callback(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const callbackSettingsLinearOauthPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /csp-violations(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const cspViolationsPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /dashboard(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const dashboardPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /docs/:section/:slug(.:format)
 * @param {any} section
 * @param {any} slug
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const docPath: ((
  section: RequiredRouteParameter,
  slug: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /docs(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const docsPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:id/edit(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const editApplicationPath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:id/edit(.:format)
 * @param {any} applicationId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const editApplicationEnvironmentPath: ((
  applicationId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /identity/password_reset/edit(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const editIdentityPasswordResetPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/profile/generate_mcp_token(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const generateMcpTokenSettingsProfilePath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /identity/email_verification(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const identityEmailVerificationPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /identity/password_reset(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const identityPasswordResetPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /ingest/deploys(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const ingestDeploysPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /ingest/kamal(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const ingestKamalPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /ingest/ping(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const ingestPingPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /ingest(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const ingestRecordsPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /issues/:id(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const issuePath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /issues/:issue_id/comments(.:format)
 * @param {any} issueId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const issueCommentsPath: ((
  issueId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /issues(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const issuesPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/jobs/classes/:group_hash(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} groupHash
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const klassApplicationEnvironmentJobsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  groupHash: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /railwatch
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const lanternPath: ((
  options?: RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /railwatch/beacon(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const lanternBeaconPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /mcp(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const mcpPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /mcp(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const mcpDiscoveryPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /issues/:id/merge_candidates(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const mergeCandidatesIssuePath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /accounts/new(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const newAccountPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/new(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const newApplicationPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/new(.:format)
 * @param {any} applicationId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const newApplicationEnvironmentPath: ((
  applicationId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /identity/password_reset/new(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const newIdentityPasswordResetPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/conductor/action_mailbox/inbound_emails/new(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const newRailsConductorInboundEmailPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/conductor/action_mailbox/inbound_emails/sources/new(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const newRailsConductorInboundEmailSourcePath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:id/pause(.:format)
 * @param {any} applicationId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const pauseApplicationEnvironmentPath: ((
  applicationId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/active_storage/representations/redirect/:signed_blob_id/:variation_key/*filename(.:format)
 * @param {any} signedBlobId
 * @param {any} variationKey
 * @param {any} filename
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsBlobRepresentationPath: ((
  signedBlobId: RequiredRouteParameter,
  variationKey: RequiredRouteParameter,
  filename: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/active_storage/representations/proxy/:signed_blob_id/:variation_key/*filename(.:format)
 * @param {any} signedBlobId
 * @param {any} variationKey
 * @param {any} filename
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsBlobRepresentationProxyPath: ((
  signedBlobId: RequiredRouteParameter,
  variationKey: RequiredRouteParameter,
  filename: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/conductor/action_mailbox/inbound_emails/:id(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsConductorInboundEmailPath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/conductor/action_mailbox/:inbound_email_id/incinerate(.:format)
 * @param {any} inboundEmailId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsConductorInboundEmailIncineratePath: ((
  inboundEmailId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)
 * @param {any} inboundEmailId
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsConductorInboundEmailReroutePath: ((
  inboundEmailId: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/conductor/action_mailbox/inbound_emails/sources(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsConductorInboundEmailSourcesPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/conductor/action_mailbox/inbound_emails(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsConductorInboundEmailsPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/active_storage/direct_uploads(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsDirectUploadsPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/active_storage/disk/:encoded_key/*filename(.:format)
 * @param {any} encodedKey
 * @param {any} filename
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsDiskServicePath: ((
  encodedKey: RequiredRouteParameter,
  filename: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /up(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsHealthCheckPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/info(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsInfoPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/info/notes(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsInfoNotesPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/info/properties(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsInfoPropertiesPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/info/routes(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsInfoRoutesPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/mailers(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsMailersPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsMailgunInboundEmailsPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/action_mailbox/mandrill/inbound_emails(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsMandrillInboundEmailsPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/action_mailbox/mandrill/inbound_emails(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsMandrillInboundHealthCheckPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/action_mailbox/postmark/inbound_emails(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsPostmarkInboundEmailsPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/action_mailbox/relay/inbound_emails(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsRelayInboundEmailsPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/action_mailbox/sendgrid/inbound_emails(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsSendgridInboundEmailsPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/active_storage/blobs/redirect/:signed_id/*filename(.:format)
 * @param {any} signedId
 * @param {any} filename
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsServiceBlobPath: ((
  signedId: RequiredRouteParameter,
  filename: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/active_storage/blobs/proxy/:signed_id/*filename(.:format)
 * @param {any} signedId
 * @param {any} filename
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const railsServiceBlobProxyPath: ((
  signedId: RequiredRouteParameter,
  filename: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /ready(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const readinessCheckPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/invitations/:id/resend(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const resendSettingsInvitationPath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /alerts/:id/retry(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const retryAlertPath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/profile/revoke_mcp_token(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const revokeMcpTokenSettingsProfilePath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const rootPath: ((
  options?: RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:id/rotate_token(.:format)
 * @param {any} applicationId
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const rotateTokenApplicationEnvironmentPath: ((
  applicationId: RequiredRouteParameter,
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /apps/:application_id/envs/:environment_id/requests/routes/:group_hash(.:format)
 * @param {any} applicationId
 * @param {any} environmentId
 * @param {any} groupHash
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const routeApplicationEnvironmentRequestsPath: ((
  applicationId: RequiredRouteParameter,
  environmentId: RequiredRouteParameter,
  groupHash: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/integrations/:id/send_test(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const sendTestSettingsIntegrationPath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /sessions/:id(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const sessionPath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/alert_rules/:id(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const settingsAlertRulePath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/alert_rules(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const settingsAlertRulesPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/appearance(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const settingsAppearancePath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/linear_oauth/:id(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const settingsDisconnectLinearOauthPath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/email(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const settingsEmailPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/integrations/:id(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const settingsIntegrationPath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/integrations(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const settingsIntegrationsPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/invitations/:id(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const settingsInvitationPath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/invitations(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const settingsInvitationsPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/linear_oauth(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const settingsLinearOauthPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/members/:id(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const settingsMemberPath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/members(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const settingsMembersPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/password(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const settingsPasswordPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/profile(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const settingsProfilePath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/sessions(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const settingsSessionsPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /sign_in(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const signInPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /sign_up(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const signUpPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /accounts/:id/switch(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const switchAccountPath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /settings/members/:id/transfer_ownership(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const transferOwnershipSettingsMemberPath: ((
  id: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /rails/active_storage/disk/:encoded_token(.:format)
 * @param {any} encodedToken
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const updateRailsDiskServicePath: ((
  encodedToken: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /users(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const usersPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /webhooks/linear(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const webhooksLinearPath: ((
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;

/**
 * Generates rails route to
 * /.well-known/mcp.json
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const wellKnownMcpPath: ((
  options?: RouteOptions
) => string) & RouteHelperExtras;

